### PR TITLE
fix mana charge spd

### LINKED ISSUE #12: Mana charge speed on created wand stuck on 2.
image

Things tried:
- Researching a bunch of wands
- Clearing all save data, validating files.
- Cloning from github, using workshop version.

I would assume this is a datastore issue, but I'm not sure.

### PR DESCRIPTION
**Pull request by CredibleOpossum**
Fixes #12 

This was a very tricky problem for me, just for it to be a one-line change haha.

Would like @Tmktahu to confirm this fix.

### CODE REVIEW

**Comment by Tmktahu** [comment]
@CredibleOpossum do you need to tweak the variable name at this location as well?

https://github.com/codefaux/persistence/blob/3fad35b9c93fe6f2bec14a21140970ec95fabb42/files/data_store.lua#L482

**Comment by CredibleOpossum** [comment]
> @CredibleOpossum do you need to tweak the variable name at this location as well?
> 
> https://github.com/codefaux/persistence/blob/3fad35b9c93fe6f2bec14a21140970ec95fabb42/files/data_store.lua#L482

I'm honestly not sure.

maybe I should change the reference below instead?

**Comment by Tmktahu** [comment]
Yea there's another instance of it at https://github.com/codefaux/persistence/blob/267e0b429bf019e426b353a2fbde404901fe265d/files/gui/fourslot.lua#L162

You could instead change the `b_mana_charge_speed_max` down here to `b_mana_charge_speed` instead. might be a smaller, safer change
https://github.com/codefaux/persistence/blob/267e0b429bf019e426b353a2fbde404901fe265d/files/data_store.lua#L658

**Comment by CredibleOpossum** [comment]
> Yea there's another instance of it at
> 
> https://github.com/codefaux/persistence/blob/267e0b429bf019e426b353a2fbde404901fe265d/files/gui/fourslot.lua#L162
> 
> You could instead change the `b_mana_charge_speed_max` down here to `b_mana_charge_speed` instead. might be a smaller, safer change
> 
> https://github.com/codefaux/persistence/blob/267e0b429bf019e426b353a2fbde404901fe265d/files/data_store.lua#L658

Yep, just noticed that too.

My bad, fixed.

**Comment by CredibleOpossum** [comment]
Can you confirm if it's working for you?

**Comment by Tmktahu** [comment]
I'm not quite sure how to test it locally in a dev environment. Tbh it's already broken so I would just send it lol. I can totally test it in-game once the deployment updates and whatnot

**Comment by CredibleOpossum** [comment]
That sounds good, I think the maintainer said he couldn't replicate it?

if you ever get a chance to test it (test env not required) you can just clone it into your /mods/ folder in noita.

**Comment by Tmktahu** [comment]
Gotcha, that's what I needed to know.

I can confirm that this change fixes the issue for me locally. cc @codefaux

**Comment by codefaux** [comment]
Hey guys, awesome work. Thanks for that. I couldn't reproduce the problem on my end, I tried new saves and profiles, but looking at the fix and reflecting on the code, you've got it exactly right. Good find.

Apologies for missing the discussion, Github isn't notifying me of _anything_ on this repo so I need to have a word with it. Good call on the @ there, @Tmktahu 

I'll merge this, pack it, and push it to the workshop. Sorry I've been absent, real life has been a bit much for me to keep up with everything.

Both @Tmktahu  and @CredibleOpossum -- I'm adding a credits section somewhere eventually, for community members who help with things like this. I'd like to address you there. Are you alright with that? How would you prefer to be listed?

**Comment by codefaux** [comment]
Also re: local environment;

Make a `mods` folder in your Noita install

Download the repo as a .zip and unpack it  into the `mods` folder, make sure the new folder is named `persistence` -- the folder name is hard-coded into Noita mods. 

You should wind up with `Noita/Mods/persistence/init.lua` etc

When you run the game, you'll have two Persistence mods. One will have a workshop icon, the other won't.

If you run noita_dev.exe instead of noita.exe, the game also shows a data console, as well as running more debugging in the background when errors occur. For mod crashes and such, the data from that console can be invaluable, BUT the game runs much worse, and **_it uses a separate set of save data_**.

**Comment by CredibleOpossum** [comment]
> Hey guys, awesome work. Thanks for that. I couldn't reproduce the problem on my end, I tried new saves and profiles, but looking at the fix and reflecting on the code, you've got it exactly right. Good find.
> 
> Apologies for missing the discussion, Github isn't notifying me of _anything_ on this repo so I need to have a word with it. Good call on the @ there, @Tmktahu
> 
> I'll merge this, pack it, and push it to the workshop. Sorry I've been absent, real life has been a bit much for me to keep up with everything.
> 
> Both @Tmktahu and @CredibleOpossum -- I'm adding a credits section somewhere eventually, for community members who help with things like this. I'd like to address you there. Are you alright with that? How would you prefer to be listed?

However you feel works, it might be cool to have credits button somewhere within the mod. profile picture + github handle would be best I think.

Let me know how against you would be against opinionated refactoring (ripping out/changing a lot of code that doesn't seem to sense to me). Let me know about #13 as well.

When debugging I put a 

```
print = MyOwnPrintFunction()
```

at the top of init.lua because the performance on noita_dev is horrible.

@codefaux in case it doesn't want to notify you haha

**Comment by Tmktahu** [comment]
@codefaux You're more than welcome to credit me as you see fit. I don't really care about credit myself, so no opinions here lol.

Also ty for the tips regarding the dev environment. I'll take note and use them in the future.

**Pull request merged**
